### ISSUE TITLE
CSIRT Komisi Pemilihan Umum ( KPU )

### ISSUE THREAD

**Issue by subagjarobi158** [atoz-chevara/csirt-indo-gov#1]
Alamat CSIRT [ Komisi Pemilihan Umum (KPU) ]
Website : [ - ]
Email : [ csirt@kpu.go.id ] 
Reward : i don't know I just send a report and then they fixing my findings without any response hahaha funny right?

**Comment by atoz-chevara** [comment]
it's like Bawaslu...hahaha...thanks bung @subagjarobi158 atas informasi'a. [[done]](https://github.com/atoz-chevara/csirt-indo-gov/commit/89ab1b70875d24be8df59af784e16078c877c006).
